# Generated by Django 2.2 on 2020-04-01 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Первая колонка')),
                ('col_2', models.CharField(blank=True, max_length=250, null=True)),
                ('col_3', models.CharField(blank=True, max_length=250, null=True)),
                ('col_4', models.CharField(blank=True, max_length=250, null=True)),
                ('col_5', models.CharField(blank=True, max_length=250, null=True)),
                ('col_6', models.CharField(blank=True, max_length=250, null=True)),
                ('col_7', models.CharField(blank=True, max_length=250, null=True)),
                ('col_8', models.CharField(blank=True, max_length=250, null=True)),
                ('col_9', models.CharField(blank=True, max_length=250, null=True)),
                ('col_10', models.CharField(blank=True, max_length=250, null=True)),
                ('col_11', models.CharField(blank=True, max_length=250, null=True)),
                ('col_12', models.CharField(blank=True, max_length=250, null=True)),
                ('col_13', models.CharField(blank=True, max_length=250, null=True)),
                ('col_14', models.CharField(blank=True, max_length=250, null=True)),
                ('col_15', models.CharField(blank=True, max_length=250, null=True)),
                ('col_16', models.CharField(blank=True, max_length=250, null=True)),
                ('col_17', models.CharField(blank=True, max_length=250, null=True)),
                ('col_18', models.CharField(blank=True, max_length=250, null=True)),
                ('col_19', models.CharField(blank=True, max_length=250, null=True)),
                ('col_20', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTable',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('col_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Первая колонка')),
                ('col_2', models.CharField(blank=True, max_length=250, null=True)),
                ('col_3', models.CharField(blank=True, max_length=250, null=True)),
                ('col_4', models.CharField(blank=True, max_length=250, null=True)),
                ('col_5', models.CharField(blank=True, max_length=250, null=True)),
                ('col_6', models.CharField(blank=True, max_length=250, null=True)),
                ('col_7', models.CharField(blank=True, max_length=250, null=True)),
                ('col_8', models.CharField(blank=True, max_length=250, null=True)),
                ('col_9', models.CharField(blank=True, max_length=250, null=True)),
                ('col_10', models.CharField(blank=True, max_length=250, null=True)),
                ('col_11', models.CharField(blank=True, max_length=250, null=True)),
                ('col_12', models.CharField(blank=True, max_length=250, null=True)),
                ('col_13', models.CharField(blank=True, max_length=250, null=True)),
                ('col_14', models.CharField(blank=True, max_length=250, null=True)),
                ('col_15', models.CharField(blank=True, max_length=250, null=True)),
                ('col_16', models.CharField(blank=True, max_length=250, null=True)),
                ('col_17', models.CharField(blank=True, max_length=250, null=True)),
                ('col_18', models.CharField(blank=True, max_length=250, null=True)),
                ('col_19', models.CharField(blank=True, max_length=250, null=True)),
                ('col_20', models.CharField(blank=True, max_length=250, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Таблица',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
