# Generated by Django 2.2 on 2020-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['id'], 'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблица'},
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='col_21',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Найден (да/нет)'),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='col_22',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='находится на дозвоне (да/нет)'),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='col_23',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Выбыл из РК'),
        ),
        migrations.AddField(
            model_name='table',
            name='col_21',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Найден (да/нет)'),
        ),
        migrations.AddField(
            model_name='table',
            name='col_22',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='находится на дозвоне (да/нет)'),
        ),
        migrations.AddField(
            model_name='table',
            name='col_23',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Выбыл из РК'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_10',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место и сроки пребывания в последние 14 дней до прибытия в Казахстан (укажите страну, область, штат и т.д.)'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_11',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='номер по базе'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_12',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='поставлен на учет в прогу'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_13',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='дата постановки в прогу'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_14',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_15',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место жительство, либо предпологаемое место проживания'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_16',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_17',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='заражен'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_18',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Госпитализирован (да/нет)'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_19',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место госпитализации'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_20',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ИИН, ФИО, моб. тел проживающие вместе в домашнем карантине'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_7',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='прошли проверку ИИН'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_8',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер мобильного телефона'),
        ),
        migrations.AlterField(
            model_name='historicaltable',
            name='col_9',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер2'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_10',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место и сроки пребывания в последние 14 дней до прибытия в Казахстан (укажите страну, область, штат и т.д.)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_11',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='номер по базе'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_12',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='поставлен на учет в прогу'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_13',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='дата постановки в прогу'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_14',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_15',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место жительство, либо предпологаемое место проживания'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_16',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_17',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='заражен'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_18',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Госпитализирован (да/нет)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_19',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место госпитализации'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_20',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ИИН, ФИО, моб. тел проживающие вместе в домашнем карантине'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_7',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='прошли проверку ИИН'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_8',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер мобильного телефона'),
        ),
        migrations.AlterField(
            model_name='table',
            name='col_9',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер2'),
        ),
    ]
