# Generated by Django 2.2 on 2020-04-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200401_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('0', 'Провал'), ('1', 'Успеч')], default='0', max_length=1, verbose_name='Статус документа'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='status',
            field=models.CharField(choices=[('0', 'Провал'), ('1', 'Успеч')], default='0', max_length=1, verbose_name='Статус документа'),
        ),
    ]
